/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShipmentMilestone = IDL.Record({
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : IDL.Text,
});
export const Shipment = IDL.Record({
  'status' : IDL.Text,
  'destination' : IDL.Text,
  'origin' : IDL.Text,
  'estimatedDelivery' : IDL.Text,
  'trackingId' : IDL.Text,
  'currentLocation' : IDL.Text,
  'milestones' : IDL.Vec(ShipmentMilestone),
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'dropLocation' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'pickupLocation' : IDL.Text,
});

export const idlService = IDL.Service({
  'addShipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ShipmentMilestone),
      ],
      [],
      [],
    ),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'initializeShipments' : IDL.Func([], [], []),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'trackShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
  'updateMilestone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShipmentMilestone = IDL.Record({
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  const Shipment = IDL.Record({
    'status' : IDL.Text,
    'destination' : IDL.Text,
    'origin' : IDL.Text,
    'estimatedDelivery' : IDL.Text,
    'trackingId' : IDL.Text,
    'currentLocation' : IDL.Text,
    'milestones' : IDL.Vec(ShipmentMilestone),
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'dropLocation' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  
  return IDL.Service({
    'addShipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ShipmentMilestone),
        ],
        [],
        [],
      ),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'initializeShipments' : IDL.Func([], [], []),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'trackShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
    'updateMilestone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };